/Users/pari/pcc-llms/output/task_id_1/task_id_1-gpt-4-temp_0.75-k_5.dfy(3,8): Error: file /path/to/file/operations/library.dfy not found
  |
3 | include "/path/to/file/operations/library.dfy"
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 parse errors detected in task_id_1-gpt-4-temp_0.75-k_5.dfy
